/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AgentsRequest } from "./AgentsRequest.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { InstallersResponse } from "./InstallersResponse.ts";

/**
 * InstallersResponse
 * @description Successful Response
 */
export type AgentsInstallersApiV1AgentsInstallersPost200 = InstallersResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AgentsInstallersApiV1AgentsInstallersPost422 = HTTPValidationError;

/**
 * AgentsRequest
 */
export type AgentsInstallersApiV1AgentsInstallersPostMutationRequest =
  AgentsRequest;

export type AgentsInstallersApiV1AgentsInstallersPostMutationResponse =
  AgentsInstallersApiV1AgentsInstallersPost200;

export type AgentsInstallersApiV1AgentsInstallersPostMutation = {
  Response: AgentsInstallersApiV1AgentsInstallersPost200;
  Request: AgentsInstallersApiV1AgentsInstallersPostMutationRequest;
  Errors: AgentsInstallersApiV1AgentsInstallersPost422;
};
