/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AgentsRequest } from "./AgentsRequest.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { IncentivesResponse } from "./IncentivesResponse.ts";

/**
 * IncentivesResponse
 * @description Successful Response
 */
export type AgentsIncentivesApiV1AgentsIncentivesPost200 = IncentivesResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AgentsIncentivesApiV1AgentsIncentivesPost422 = HTTPValidationError;

/**
 * AgentsRequest
 */
export type AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest =
  AgentsRequest;

export type AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse =
  AgentsIncentivesApiV1AgentsIncentivesPost200;

export type AgentsIncentivesApiV1AgentsIncentivesPostMutation = {
  Response: AgentsIncentivesApiV1AgentsIncentivesPost200;
  Request: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest;
  Errors: AgentsIncentivesApiV1AgentsIncentivesPost422;
};
