/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AgentsRequest
 * @description Request for agent analysis after solar analysis
 */
export type AgentsRequest = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @minLength -90
   * @maxLength 90
   * @type number
   */
  latitude: number;
  /**
   * @minLength -180
   * @maxLength 180
   * @type number
   */
  longitude: number;
  /**
   * @type string
   */
  address: string;
  /**
   * @type number
   */
  system_size_kw: number;
  /**
   * @type integer
   */
  annual_generation_kwh: number;
  state?: string | null;
  zip_code?: string | null;
  /**
   * @description User-drawn polygon coordinates as [[lat, lng], [lat, lng], ...]
   */
  user_polygon?: number[][] | null;
};
