/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
  /**
   * @minLength -90
   * @maxLength 90
   * @type number
   */
  latitude: number;
  /**
   * @minLength -180
   * @maxLength 180
   * @type number
   */
  longitude: number;
  /**
   * @default ""
   * @type string | undefined
   */
  address?: string;
  /**
   * @description State/territory code (e.g., CA for US, DL for India). Auto-detected for India.
   * @minLength 2
   * @maxLength 2
   * @type string | undefined
   */
  state?: string | null;
  zip_code?: string | null;
  /**
   * @description ISO 3166-1 alpha-2 country code. Auto-detected from coordinates if not provided.
   * @type string | undefined
   */
  country?: string | null;
  /**
   * @description User-drawn polygon coordinates as [[lat, lng], [lat, lng], ...], minimum 3 points
   */
  user_polygon?: number[][] | null;
};
