/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AnalysisResponse } from "./AnalysisResponse.ts";
import type { AnalyzeRequest } from "./AnalyzeRequest.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

/**
 * AnalysisResponse
 * @description Successful Response
 */
export type AnalyzeApiV1AnalyzePost200 = AnalysisResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type AnalyzeApiV1AnalyzePost422 = HTTPValidationError;

/**
 * AnalyzeRequest
 */
export type AnalyzeApiV1AnalyzePostMutationRequest = AnalyzeRequest;

export type AnalyzeApiV1AnalyzePostMutationResponse =
  AnalyzeApiV1AnalyzePost200;

export type AnalyzeApiV1AnalyzePostMutation = {
  Response: AnalyzeApiV1AnalyzePost200;
  Request: AnalyzeApiV1AnalyzePostMutationRequest;
  Errors: AnalyzeApiV1AnalyzePost422;
};
