/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { EquityAnalysisResponse } from "./EquityAnalysisResponse.ts";
import type { FinancialOutlook } from "./FinancialOutlook.ts";
import type { Location } from "./Location.ts";
import type { RoofAnalysis } from "./RoofAnalysis.ts";
import type { SolarData } from "./SolarData.ts";
import type { SolarPotential } from "./SolarPotential.ts";
import type { SolarScoreBreakdown } from "./SolarScoreBreakdown.ts";

/**
 * AnalysisResponse
 */
export type AnalysisResponse = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @type string, date-time
   */
  timestamp: string;
  /**
   * @type object
   */
  location: Location;
  /**
   * @type object
   */
  roof_analysis: RoofAnalysis;
  /**
   * @type object
   */
  solar_data: SolarData;
  /**
   * @type object
   */
  solar_potential: SolarPotential;
  /**
   * @type integer
   */
  solar_score: number;
  solar_score_breakdown?: SolarScoreBreakdown | null;
  /**
   * @description Key financial metrics derived from the financial analysis module.
   * @type object
   */
  financial_outlook: FinancialOutlook;
  equity_analysis?: EquityAnalysisResponse | null;
};
