/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
  /**
   * @minLength -90
   * @maxLength 90
   * @type number
   */
  latitude: number;
  /**
   * @minLength -180
   * @maxLength 180
   * @type number
   */
  longitude: number;
  /**
   * @default ""
   * @type string | undefined
   */
  address?: string;
  /**
   * @description US state/territory code (e.g., CA)
   * @minLength 2
   * @maxLength 2
   * @type string
   */
  state: string;
  zip_code?: string | null;
  /**
   * @description User-drawn polygon coordinates as [[lat, lng], [lat, lng], ...], minimum 3 points
   */
  user_polygon?: number[][] | null;
};
