/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * BillComparisonResponse
 * @description Bill comparison before/after solar installation.
 */
export type BillComparisonResponse = {
  /**
   * @type number
   */
  current_monthly_bill: number;
  /**
   * @type number
   */
  new_monthly_bill: number;
};
