/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BillComparisonResponse } from "./BillComparisonResponse.ts";
import type { BodyBillComparisonApiV1BillComparisonPost } from "./BodyBillComparisonApiV1BillComparisonPost.ts";
import type { HTTPValidationError } from "./HTTPValidationError.ts";

/**
 * BillComparisonResponse
 * @description Successful Response
 */
export type BillComparisonApiV1BillComparisonPost200 = BillComparisonResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type BillComparisonApiV1BillComparisonPost422 = HTTPValidationError;

/**
 * Body_bill_comparison_api_v1_bill_comparison_post
 */
export type BillComparisonApiV1BillComparisonPostMutationRequest =
  BodyBillComparisonApiV1BillComparisonPost;

export type BillComparisonApiV1BillComparisonPostMutationResponse =
  BillComparisonApiV1BillComparisonPost200;

export type BillComparisonApiV1BillComparisonPostMutation = {
  Response: BillComparisonApiV1BillComparisonPost200;
  Request: BillComparisonApiV1BillComparisonPostMutationRequest;
  Errors: BillComparisonApiV1BillComparisonPost422;
};
