/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * BlockGroupEquityData
 * @description Equity data for a single Census block group.
 */
export type BlockGroupEquityData = {
  /**
   * @type string
   */
  block_group_id: string;
  /**
   * @minLength -90
   * @maxLength 90
   * @type number
   */
  lat: number;
  /**
   * @minLength -180
   * @maxLength 180
   * @type number
   */
  lng: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @type number
   */
  equity_score: number;
  /**
   * @type number
   */
  median_income: number;
  /**
   * @type number
   */
  renter_percentage: number;
  /**
   * @type number
   */
  energy_burden: number;
  /**
   * @type integer
   */
  solar_installations: number;
  /**
   * @type integer
   */
  total_households: number;
  /**
   * @type array
   */
  barriers: string[];
};
