/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Body_bill_comparison_api_v1_bill_comparison_post
 */
export type BodyBillComparisonApiV1BillComparisonPost = {
  /**
   * @description Electricity bill PDF file
   * @type string
   */
  file: Blob;
  /**
   * @type number
   */
  first_year_savings_net: number;
  /**
   * @type number
   */
  payback_period_years: number;
  /**
   * @type number
   */
  monthly_savings: number;
};
