/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * EquityScoreBreakdown
 * @description Detailed breakdown of equity score components.
 */
export type EquityScoreBreakdown = {
  /**
   * @minLength 0
   * @maxLength 100
   * @type number
   */
  total_score: number;
  /**
   * @minLength 0
   * @maxLength 40
   * @type number
   */
  income_component: number;
  /**
   * @minLength 0
   * @maxLength 30
   * @type number
   */
  ownership_component: number;
  /**
   * @minLength 0
   * @maxLength 20
   * @type number
   */
  burden_component: number;
  /**
   * @minLength 0
   * @maxLength 10
   * @type number
   */
  adoption_component: number;
  /**
   * @type array | undefined
   */
  barriers?: string[];
};
