/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BlockGroupEquityData } from "./BlockGroupEquityData.ts";
import type { EquityScoreBreakdown } from "./EquityScoreBreakdown.ts";

/**
 * EquityAnalysisResponse
 * @description Response model for equity analysis API.
 */
export type EquityAnalysisResponse = {
  /**
   * @description Detailed breakdown of equity score components.
   * @type object
   */
  user_address_score: EquityScoreBreakdown;
  /**
   * @type array
   */
  neighborhood_data: BlockGroupEquityData[];
  /**
   * @description Count of block groups with score < 35
   * @type integer
   */
  solar_deserts_count: number;
  /**
   * @description e.g., \'Princeton, NJ area\'
   * @type string
   */
  area_description: string;
};
