/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * FinancialOutlook
 * @description Key financial metrics derived from the financial analysis module.
 */
export type FinancialOutlook = {
  /**
   * @type number
   */
  system_cost_net: number;
  /**
   * @type number
   */
  total_net_savings_25_years: number;
  /**
   * @type number
   */
  net_profit_25_years: number;
  /**
   * @type number
   */
  payback_period_years: number;
  /**
   * @type number
   */
  roi_25_years: number;
  /**
   * @type number
   */
  first_year_savings_gross: number;
  /**
   * @type number
   */
  first_year_savings_net: number;
  /**
   * @default "USD"
   * @type string
   */
  currency?: string;
};
