/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * IncentivesResponse
 * @description Solar incentives and rebates search results.
 */
export type IncentivesResponse = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @type string, date-time
   */
  generated_at: string;
  /**
   * @type string
   */
  incentives_markdown: string;
  /**
   * @type string
   */
  model_name: string;
};
