/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * InstallersResponse
 * @description Solar installers search results.
 */
export type InstallersResponse = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @type string, date-time
   */
  generated_at: string;
  /**
   * @type string
   */
  installers_markdown: string;
  /**
   * @type string
   */
  model_name: string;
};
