/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Location
 */
export type Location = {
  /**
   * @type number
   */
  latitude: number;
  /**
   * @type number
   */
  longitude: number;
  /**
   * @type string
   */
  address: string;
};
