/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * Obstacles
 */
export type Obstacles = {
  /**
   * @default 0
   * @type integer | undefined
   */
  chimneys?: number;
  /**
   * @default 0
   * @type integer | undefined
   */
  skylights?: number;
  /**
   * @default false
   * @type boolean | undefined
   */
  trees_nearby?: boolean;
  /**
   * @default 0
   * @type integer | undefined
   */
  hvac_units?: number;
};
