/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RoofPolygon } from "./RoofPolygon.ts";

/**
 * RoofSegment
 */
export type RoofSegment = {
  /**
   * @type integer
   */
  segment_id: number;
  /**
   * @type number
   */
  area_sqft: number;
  /**
   * @type integer
   */
  orientation_degrees: number;
  /**
   * @type string
   */
  orientation_cardinal: string;
  /**
   * @type number
   */
  tilt_degrees: number;
  /**
   * @type integer
   */
  panel_capacity: number;
  polygon?: RoofPolygon | null;
};
