/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * RoofPolygon
 * @description Roof polygon coordinates for frontend Google Maps overlay
 */
export type RoofPolygon = {
  /**
   * @type array
   */
  coordinates: number[][];
  /**
   * @type number
   */
  area_sqft: number;
  /**
   * @type number
   */
  confidence: number;
};
