/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Obstacles } from "./Obstacles.ts";
import type { RoofSegment } from "./RoofSegment.ts";

/**
 * RoofAnalysis
 */
export type RoofAnalysis = {
  /**
   * @type number
   */
  total_area_sqft: number;
  /**
   * @type number
   */
  usable_area_sqft: number;
  /**
   * @type array
   */
  roof_segments: RoofSegment[];
  /**
   * @type object
   */
  obstacles: Obstacles;
  /**
   * @type number
   */
  confidence_score: number;
};
