/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SeasonalVariation
 */
export type SeasonalVariation = {
  /**
   * @type number
   */
  summer_sun_hours: number;
  /**
   * @type number
   */
  winter_sun_hours: number;
};
