/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { SeasonalVariation } from "./SeasonalVariation.ts";

/**
 * SolarData
 */
export type SolarData = {
  /**
   * @type number
   */
  peak_sun_hours_daily: number;
  /**
   * @type number
   */
  annual_irradiance_kwh_m2: number;
  /**
   * @type object
   */
  seasonal_variation: SeasonalVariation;
};
