/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SolarScoreBreakdown
 * @description Detailed breakdown of how solar score was calculated
 */
export type SolarScoreBreakdown = {
  /**
   * @type object
   */
  components: {
    [key: string]: any;
  };
  /**
   * @type string
   */
  formula: string;
};
