/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SolarPotential
 */
export type SolarPotential = {
  /**
   * @type number
   */
  system_size_kw: number;
  /**
   * @type integer
   */
  annual_generation_kwh: number;
  /**
   * @type number
   */
  daily_generation_kwh: number;
  /**
   * @type number
   */
  capacity_factor: number;
  /**
   * @type integer
   */
  energy_offset_percent: number;
  /**
   * @type number
   */
  co2_offset_tons_yearly: number;
  /**
   * @type integer
   */
  co2_offset_tons_25year: number;
  /**
   * @type integer
   */
  equivalent_trees_planted: number;
};
