/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { HTTPValidationError } from "./HTTPValidationError.ts";
import type { SummaryRequest } from "./SummaryRequest.ts";
import type { SummaryResponse } from "./SummaryResponse.ts";

/**
 * SummaryResponse
 * @description Successful Response
 */
export type SummarizeMetricsApiV1SummaryPost200 = SummaryResponse;

/**
 * HTTPValidationError
 * @description Validation Error
 */
export type SummarizeMetricsApiV1SummaryPost422 = HTTPValidationError;

/**
 * SummaryRequest
 */
export type SummarizeMetricsApiV1SummaryPostMutationRequest = SummaryRequest;

export type SummarizeMetricsApiV1SummaryPostMutationResponse =
  SummarizeMetricsApiV1SummaryPost200;

export type SummarizeMetricsApiV1SummaryPostMutation = {
  Response: SummarizeMetricsApiV1SummaryPost200;
  Request: SummarizeMetricsApiV1SummaryPostMutationRequest;
  Errors: SummarizeMetricsApiV1SummaryPost422;
};
