/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FinancialOutlook } from "./FinancialOutlook.ts";
import type { Location } from "./Location.ts";
import type { SolarPotential } from "./SolarPotential.ts";

/**
 * SummaryRequest
 * @description Payload for requesting a Gemini-generated narrative summary.
 */
export type SummaryRequest = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @type object
   */
  location: Location;
  /**
   * @type object
   */
  solar_potential: SolarPotential;
  /**
   * @description Key financial metrics derived from the financial analysis module.
   * @type object
   */
  financial_outlook: FinancialOutlook;
  /**
   * @description Optional free-form notes to steer the narrative tone.
   */
  additional_context?: string | null;
};
