/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * SummaryResponse
 * @description Narrative summary generated by Gemini for the analysis metrics.
 */
export type SummaryResponse = {
  /**
   * @type string
   */
  analysis_id: string;
  /**
   * @type string, date-time
   */
  generated_at: string;
  /**
   * @type string
   */
  summary_markdown: string;
  /**
   * @type string
   */
  model_name: string;
};
