/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  AgentsInstallersApiV1AgentsInstallersPostMutationRequest,
  AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
  AgentsInstallersApiV1AgentsInstallersPost422,
} from "../models/AgentsInstallersApiV1AgentsInstallersPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getAgentsInstallersApiV1AgentsInstallersPostUrl() {
  const res = { method: "POST", url: `/api/v1/agents/installers` as const };
  return res;
}

/**
 * @description Find solar installers using Dedalus agent
 * @summary Agents Installers
 * {@link /api/v1/agents/installers}
 */
export async function agentsInstallersApiV1AgentsInstallersPost(
  data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest,
  config: Partial<
    RequestConfig<AgentsInstallersApiV1AgentsInstallersPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
    ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
    AgentsInstallersApiV1AgentsInstallersPostMutationRequest
  >({
    method: "POST",
    url: getAgentsInstallersApiV1AgentsInstallersPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
