/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest,
  AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
  AgentsIncentivesApiV1AgentsIncentivesPost422,
} from "../models/AgentsIncentivesApiV1AgentsIncentivesPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getAgentsIncentivesApiV1AgentsIncentivesPostUrl() {
  const res = { method: "POST", url: `/api/v1/agents/incentives` as const };
  return res;
}

/**
 * @description Find solar incentives using Dedalus agent
 * @summary Agents Incentives
 * {@link /api/v1/agents/incentives}
 */
export async function agentsIncentivesApiV1AgentsIncentivesPost(
  data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest,
  config: Partial<
    RequestConfig<AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
    ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
    AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest
  >({
    method: "POST",
    url: getAgentsIncentivesApiV1AgentsIncentivesPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
