/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  AnalyzeApiV1AnalyzePostMutationRequest,
  AnalyzeApiV1AnalyzePostMutationResponse,
  AnalyzeApiV1AnalyzePost422,
} from "../models/AnalyzeApiV1AnalyzePost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getAnalyzeApiV1AnalyzePostUrl() {
  const res = { method: "POST", url: `/api/v1/analyze` as const };
  return res;
}

/**
 * @description Main analysis endpoint - supports both user-drawn polygons and CV analysis
 * @summary Analyze
 * {@link /api/v1/analyze}
 */
export async function analyzeApiV1AnalyzePost(
  data: AnalyzeApiV1AnalyzePostMutationRequest,
  config: Partial<RequestConfig<AnalyzeApiV1AnalyzePostMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    AnalyzeApiV1AnalyzePostMutationResponse,
    ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
    AnalyzeApiV1AnalyzePostMutationRequest
  >({
    method: "POST",
    url: getAnalyzeApiV1AnalyzePostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
