/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  BillComparisonApiV1BillComparisonPostMutationRequest,
  BillComparisonApiV1BillComparisonPostMutationResponse,
  BillComparisonApiV1BillComparisonPost422,
} from "../models/BillComparisonApiV1BillComparisonPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";
import { buildFormData } from "../.kubb/config.ts";

function getBillComparisonApiV1BillComparisonPostUrl() {
  const res = { method: "POST", url: `/api/v1/bill-comparison` as const };
  return res;
}

/**
 * @description Compare electricity bills before and after solar installation.
 * Accepts a PDF electricity bill and extracts monthly bill amount using Gemini,
 * then calculates comparison with solar savings.
 * @summary Bill Comparison
 * {@link /api/v1/bill-comparison}
 */
export async function billComparisonApiV1BillComparisonPost(
  data: BillComparisonApiV1BillComparisonPostMutationRequest,
  config: Partial<
    RequestConfig<BillComparisonApiV1BillComparisonPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;
  const formData = buildFormData(requestData);
  const res = await request<
    BillComparisonApiV1BillComparisonPostMutationResponse,
    ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
    BillComparisonApiV1BillComparisonPostMutationRequest
  >({
    method: "POST",
    url: getBillComparisonApiV1BillComparisonPostUrl().url.toString(),
    data: formData as FormData,
    ...requestConfig,
  });
  return res.data;
}
