/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type { HealthCheckHealthGetQueryResponse } from "../models/HealthCheckHealthGet.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getHealthCheckHealthGetUrl() {
  const res = { method: "GET", url: `/health` as const };
  return res;
}

/**
 * @description Health check endpoint
 * @summary Health Check
 * {@link /health}
 */
export async function healthCheckHealthGet(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    HealthCheckHealthGetQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getHealthCheckHealthGetUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
