/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type { ReadRootGetQueryResponse } from "../models/ReadRootGet.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getReadRootGetUrl() {
  const res = { method: "GET", url: `/` as const };
  return res;
}

/**
 * @description Serve the frontend HTML
 * @summary Read Root
 * {@link /}
 */
export async function readRootGet(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    ReadRootGetQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({
    method: "GET",
    url: getReadRootGetUrl().url.toString(),
    ...requestConfig,
  });
  return res.data;
}
