/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@kubb/plugin-client/clients/fetch";
import type {
  SummarizeMetricsApiV1SummaryPostMutationRequest,
  SummarizeMetricsApiV1SummaryPostMutationResponse,
  SummarizeMetricsApiV1SummaryPost422,
} from "../models/SummarizeMetricsApiV1SummaryPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/fetch";

function getSummarizeMetricsApiV1SummaryPostUrl() {
  const res = { method: "POST", url: `/api/v1/summary` as const };
  return res;
}

/**
 * @description Generate a natural-language summary of solar metrics using Gemini.
 * @summary Summarize Metrics
 * {@link /api/v1/summary}
 */
export async function summarizeMetricsApiV1SummaryPost(
  data: SummarizeMetricsApiV1SummaryPostMutationRequest,
  config: Partial<
    RequestConfig<SummarizeMetricsApiV1SummaryPostMutationRequest>
  > & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    SummarizeMetricsApiV1SummaryPostMutationResponse,
    ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
    SummarizeMetricsApiV1SummaryPostMutationRequest
  >({
    method: "POST",
    url: getSummarizeMetricsApiV1SummaryPostUrl().url.toString(),
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}
