/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AnalyzeApiV1AnalyzePostMutationRequest,
  AnalyzeApiV1AnalyzePostMutationResponse,
  AnalyzeApiV1AnalyzePost422,
} from "../models/AnalyzeApiV1AnalyzePost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { analyzeApiV1AnalyzePost } from "../clients/analyzeApiV1AnalyzePost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const analyzeApiV1AnalyzePostMutationKey = () =>
  [{ url: "/api/v1/analyze" }] as const;

export type AnalyzeApiV1AnalyzePostMutationKey = ReturnType<
  typeof analyzeApiV1AnalyzePostMutationKey
>;

export function analyzeApiV1AnalyzePostMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<AnalyzeApiV1AnalyzePostMutationRequest>> & {
    client?: Client;
  } = {},
) {
  const mutationKey = analyzeApiV1AnalyzePostMutationKey();
  return mutationOptions<
    AnalyzeApiV1AnalyzePostMutationResponse,
    ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
    { data: AnalyzeApiV1AnalyzePostMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return analyzeApiV1AnalyzePost(data, config);
    },
  });
}

/**
 * @description Main analysis endpoint - supports both user-drawn polygons and CV analysis
 * @summary Analyze
 * {@link /api/v1/analyze}
 */
export function useAnalyzeApiV1AnalyzePost<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AnalyzeApiV1AnalyzePostMutationResponse,
      ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
      { data: AnalyzeApiV1AnalyzePostMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<AnalyzeApiV1AnalyzePostMutationRequest>> & {
      client?: Client;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? analyzeApiV1AnalyzePostMutationKey();

  const baseOptions = analyzeApiV1AnalyzePostMutationOptions(
    config,
  ) as UseMutationOptions<
    AnalyzeApiV1AnalyzePostMutationResponse,
    ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
    { data: AnalyzeApiV1AnalyzePostMutationRequest },
    TContext
  >;

  return useMutation<
    AnalyzeApiV1AnalyzePostMutationResponse,
    ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
    { data: AnalyzeApiV1AnalyzePostMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AnalyzeApiV1AnalyzePostMutationResponse,
    ResponseErrorConfig<AnalyzeApiV1AnalyzePost422>,
    { data: AnalyzeApiV1AnalyzePostMutationRequest },
    TContext
  >;
}
