/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest,
  AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
  AgentsIncentivesApiV1AgentsIncentivesPost422,
} from "../models/AgentsIncentivesApiV1AgentsIncentivesPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { agentsIncentivesApiV1AgentsIncentivesPost } from "../clients/agentsIncentivesApiV1AgentsIncentivesPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const agentsIncentivesApiV1AgentsIncentivesPostMutationKey = () =>
  [{ url: "/api/v1/agents/incentives" }] as const;

export type AgentsIncentivesApiV1AgentsIncentivesPostMutationKey = ReturnType<
  typeof agentsIncentivesApiV1AgentsIncentivesPostMutationKey
>;

export function agentsIncentivesApiV1AgentsIncentivesPostMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = agentsIncentivesApiV1AgentsIncentivesPostMutationKey();
  return mutationOptions<
    AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
    ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
    { data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return agentsIncentivesApiV1AgentsIncentivesPost(data, config);
    },
  });
}

/**
 * @description Find solar incentives using Dedalus agent
 * @summary Agents Incentives
 * {@link /api/v1/agents/incentives}
 */
export function useAgentsIncentivesApiV1AgentsIncentivesPost<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
      ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
      { data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    agentsIncentivesApiV1AgentsIncentivesPostMutationKey();

  const baseOptions = agentsIncentivesApiV1AgentsIncentivesPostMutationOptions(
    config,
  ) as UseMutationOptions<
    AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
    ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
    { data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest },
    TContext
  >;

  return useMutation<
    AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
    ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
    { data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AgentsIncentivesApiV1AgentsIncentivesPostMutationResponse,
    ResponseErrorConfig<AgentsIncentivesApiV1AgentsIncentivesPost422>,
    { data: AgentsIncentivesApiV1AgentsIncentivesPostMutationRequest },
    TContext
  >;
}
