/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  AgentsInstallersApiV1AgentsInstallersPostMutationRequest,
  AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
  AgentsInstallersApiV1AgentsInstallersPost422,
} from "../models/AgentsInstallersApiV1AgentsInstallersPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { agentsInstallersApiV1AgentsInstallersPost } from "../clients/agentsInstallersApiV1AgentsInstallersPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const agentsInstallersApiV1AgentsInstallersPostMutationKey = () =>
  [{ url: "/api/v1/agents/installers" }] as const;

export type AgentsInstallersApiV1AgentsInstallersPostMutationKey = ReturnType<
  typeof agentsInstallersApiV1AgentsInstallersPostMutationKey
>;

export function agentsInstallersApiV1AgentsInstallersPostMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<AgentsInstallersApiV1AgentsInstallersPostMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = agentsInstallersApiV1AgentsInstallersPostMutationKey();
  return mutationOptions<
    AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
    ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
    { data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return agentsInstallersApiV1AgentsInstallersPost(data, config);
    },
  });
}

/**
 * @description Find solar installers using Dedalus agent
 * @summary Agents Installers
 * {@link /api/v1/agents/installers}
 */
export function useAgentsInstallersApiV1AgentsInstallersPost<TContext>(
  options: {
    mutation?: UseMutationOptions<
      AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
      ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
      { data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<AgentsInstallersApiV1AgentsInstallersPostMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    agentsInstallersApiV1AgentsInstallersPostMutationKey();

  const baseOptions = agentsInstallersApiV1AgentsInstallersPostMutationOptions(
    config,
  ) as UseMutationOptions<
    AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
    ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
    { data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest },
    TContext
  >;

  return useMutation<
    AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
    ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
    { data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    AgentsInstallersApiV1AgentsInstallersPostMutationResponse,
    ResponseErrorConfig<AgentsInstallersApiV1AgentsInstallersPost422>,
    { data: AgentsInstallersApiV1AgentsInstallersPostMutationRequest },
    TContext
  >;
}
