/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  BillComparisonApiV1BillComparisonPostMutationRequest,
  BillComparisonApiV1BillComparisonPostMutationResponse,
  BillComparisonApiV1BillComparisonPost422,
} from "../models/BillComparisonApiV1BillComparisonPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { billComparisonApiV1BillComparisonPost } from "../clients/billComparisonApiV1BillComparisonPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const billComparisonApiV1BillComparisonPostMutationKey = () =>
  [{ url: "/api/v1/bill-comparison" }] as const;

export type BillComparisonApiV1BillComparisonPostMutationKey = ReturnType<
  typeof billComparisonApiV1BillComparisonPostMutationKey
>;

export function billComparisonApiV1BillComparisonPostMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<BillComparisonApiV1BillComparisonPostMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = billComparisonApiV1BillComparisonPostMutationKey();
  return mutationOptions<
    BillComparisonApiV1BillComparisonPostMutationResponse,
    ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
    { data: BillComparisonApiV1BillComparisonPostMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return billComparisonApiV1BillComparisonPost(data, config);
    },
  });
}

/**
 * @description Compare electricity bills before and after solar installation.
 * Accepts a PDF electricity bill and extracts monthly bill amount using Gemini,
 * then calculates comparison with solar savings.
 * @summary Bill Comparison
 * {@link /api/v1/bill-comparison}
 */
export function useBillComparisonApiV1BillComparisonPost<TContext>(
  options: {
    mutation?: UseMutationOptions<
      BillComparisonApiV1BillComparisonPostMutationResponse,
      ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
      { data: BillComparisonApiV1BillComparisonPostMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<BillComparisonApiV1BillComparisonPostMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    billComparisonApiV1BillComparisonPostMutationKey();

  const baseOptions = billComparisonApiV1BillComparisonPostMutationOptions(
    config,
  ) as UseMutationOptions<
    BillComparisonApiV1BillComparisonPostMutationResponse,
    ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
    { data: BillComparisonApiV1BillComparisonPostMutationRequest },
    TContext
  >;

  return useMutation<
    BillComparisonApiV1BillComparisonPostMutationResponse,
    ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
    { data: BillComparisonApiV1BillComparisonPostMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    BillComparisonApiV1BillComparisonPostMutationResponse,
    ResponseErrorConfig<BillComparisonApiV1BillComparisonPost422>,
    { data: BillComparisonApiV1BillComparisonPostMutationRequest },
    TContext
  >;
}
