/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ReadRootGetQueryResponse } from "../models/ReadRootGet.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { readRootGet } from "../clients/readRootGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const readRootGetSuspenseQueryKey = () => [{ url: "/" }] as const;

export type ReadRootGetSuspenseQueryKey = ReturnType<
  typeof readRootGetSuspenseQueryKey
>;

export function readRootGetSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = readRootGetSuspenseQueryKey();
  return queryOptions<
    ReadRootGetQueryResponse,
    ResponseErrorConfig<Error>,
    ReadRootGetQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return readRootGet({ ...config, signal: config.signal ?? signal });
    },
  });
}

/**
 * @description Serve the frontend HTML
 * @summary Read Root
 * {@link /}
 */
export function useReadRootGetSuspense<
  TData = ReadRootGetQueryResponse,
  TQueryKey extends QueryKey = ReadRootGetSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        ReadRootGetQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? readRootGetSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...readRootGetSuspenseQueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
