/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  SummarizeMetricsApiV1SummaryPostMutationRequest,
  SummarizeMetricsApiV1SummaryPostMutationResponse,
  SummarizeMetricsApiV1SummaryPost422,
} from "../models/SummarizeMetricsApiV1SummaryPost.ts";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@kubb/plugin-client/clients/axios";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { summarizeMetricsApiV1SummaryPost } from "../clients/summarizeMetricsApiV1SummaryPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const summarizeMetricsApiV1SummaryPostMutationKey = () =>
  [{ url: "/api/v1/summary" }] as const;

export type SummarizeMetricsApiV1SummaryPostMutationKey = ReturnType<
  typeof summarizeMetricsApiV1SummaryPostMutationKey
>;

export function summarizeMetricsApiV1SummaryPostMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<SummarizeMetricsApiV1SummaryPostMutationRequest>
  > & { client?: Client } = {},
) {
  const mutationKey = summarizeMetricsApiV1SummaryPostMutationKey();
  return mutationOptions<
    SummarizeMetricsApiV1SummaryPostMutationResponse,
    ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
    { data: SummarizeMetricsApiV1SummaryPostMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return summarizeMetricsApiV1SummaryPost(data, config);
    },
  });
}

/**
 * @description Generate a natural-language summary of solar metrics using Gemini.
 * @summary Summarize Metrics
 * {@link /api/v1/summary}
 */
export function useSummarizeMetricsApiV1SummaryPost<TContext>(
  options: {
    mutation?: UseMutationOptions<
      SummarizeMetricsApiV1SummaryPostMutationResponse,
      ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
      { data: SummarizeMetricsApiV1SummaryPostMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<SummarizeMetricsApiV1SummaryPostMutationRequest>
    > & { client?: Client };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    summarizeMetricsApiV1SummaryPostMutationKey();

  const baseOptions = summarizeMetricsApiV1SummaryPostMutationOptions(
    config,
  ) as UseMutationOptions<
    SummarizeMetricsApiV1SummaryPostMutationResponse,
    ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
    { data: SummarizeMetricsApiV1SummaryPostMutationRequest },
    TContext
  >;

  return useMutation<
    SummarizeMetricsApiV1SummaryPostMutationResponse,
    ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
    { data: SummarizeMetricsApiV1SummaryPostMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    SummarizeMetricsApiV1SummaryPostMutationResponse,
    ResponseErrorConfig<SummarizeMetricsApiV1SummaryPost422>,
    { data: SummarizeMetricsApiV1SummaryPostMutationRequest },
    TContext
  >;
}
