/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { agentsRequestSchema } from "./agentsRequestSchema.ts";
import { installersResponseSchema } from "./installersResponseSchema.ts";

/**
 * @description Successful Response
 */
export const agentsInstallersApiV1AgentsInstallersPost200Schema = z
  .lazy(() => installersResponseSchema)
  .describe("Solar installers search results.");

/**
 * @description Validation Error
 */
export const agentsInstallersApiV1AgentsInstallersPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
);

export const agentsInstallersApiV1AgentsInstallersPostMutationRequestSchema = z
  .lazy(() => agentsRequestSchema)
  .describe("Request for agent analysis after solar analysis");

export const agentsInstallersApiV1AgentsInstallersPostMutationResponseSchema =
  z.lazy(() => agentsInstallersApiV1AgentsInstallersPost200Schema);
