/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { agentsRequestSchema } from "./agentsRequestSchema.ts";
import { incentivesResponseSchema } from "./incentivesResponseSchema.ts";

/**
 * @description Successful Response
 */
export const agentsIncentivesApiV1AgentsIncentivesPost200Schema = z
  .lazy(() => incentivesResponseSchema)
  .describe("Solar incentives and rebates search results.");

/**
 * @description Validation Error
 */
export const agentsIncentivesApiV1AgentsIncentivesPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
);

export const agentsIncentivesApiV1AgentsIncentivesPostMutationRequestSchema = z
  .lazy(() => agentsRequestSchema)
  .describe("Request for agent analysis after solar analysis");

export const agentsIncentivesApiV1AgentsIncentivesPostMutationResponseSchema =
  z.lazy(() => agentsIncentivesApiV1AgentsIncentivesPost200Schema);
