/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Request for agent analysis after solar analysis
 */
export const agentsRequestSchema = z
  .object({
    analysis_id: z.string(),
    latitude: z.number().min(-90).max(90),
    longitude: z.number().min(-180).max(180),
    address: z.string(),
    system_size_kw: z.number(),
    annual_generation_kwh: z.number().int(),
    state: z.optional(z.union([z.string(), z.null()])),
    zip_code: z.optional(z.union([z.string(), z.null()])),
    user_polygon: z.optional(
      z
        .union([z.array(z.array(z.number())), z.null()])
        .describe(
          "User-drawn polygon coordinates as [[lat, lng], [lat, lng], ...]",
        ),
    ),
  })
  .describe("Request for agent analysis after solar analysis");
