/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { equityAnalysisResponseSchema } from "./equityAnalysisResponseSchema.ts";
import { financialOutlookSchema } from "./financialOutlookSchema.ts";
import { locationSchema } from "./locationSchema.ts";
import { roofAnalysisSchema } from "./roofAnalysisSchema.ts";
import { solarDataSchema } from "./solarDataSchema.ts";
import { solarPotentialSchema } from "./solarPotentialSchema.ts";
import { solarScoreBreakdownSchema } from "./solarScoreBreakdownSchema.ts";

export const analysisResponseSchema = z.object({
  analysis_id: z.string(),
  timestamp: z.string().datetime(),
  location: z.lazy(() => locationSchema),
  roof_analysis: z.lazy(() => roofAnalysisSchema),
  solar_data: z.lazy(() => solarDataSchema),
  solar_potential: z.lazy(() => solarPotentialSchema),
  solar_score: z.number().int(),
  solar_score_breakdown: z.optional(
    z.union([z.lazy(() => solarScoreBreakdownSchema), z.null()]),
  ),
  financial_outlook: z
    .lazy(() => financialOutlookSchema)
    .describe(
      "Key financial metrics derived from the financial analysis module.",
    ),
  equity_analysis: z.optional(
    z.union([z.lazy(() => equityAnalysisResponseSchema), z.null()]),
  ),
});
