/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { analysisResponseSchema } from "./analysisResponseSchema.ts";
import { analyzeRequestSchema } from "./analyzeRequestSchema.ts";

/**
 * @description Successful Response
 */
export const analyzeApiV1AnalyzePost200Schema = z.lazy(
  () => analysisResponseSchema,
);

/**
 * @description Validation Error
 */
export const analyzeApiV1AnalyzePost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
);

export const analyzeApiV1AnalyzePostMutationRequestSchema = z.lazy(
  () => analyzeRequestSchema,
);

export const analyzeApiV1AnalyzePostMutationResponseSchema = z.lazy(
  () => analyzeApiV1AnalyzePost200Schema,
);
