/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const analyzeRequestSchema = z.object({
  latitude: z.number().min(-90).max(90),
  longitude: z.number().min(-180).max(180),
  address: z.optional(z.string().default("")),
  state: z
    .string()
    .min(2)
    .max(2)
    .describe("US state/territory code (e.g., CA)"),
  zip_code: z.optional(z.union([z.string(), z.null()])),
  user_polygon: z.optional(
    z
      .union([z.array(z.array(z.number())), z.null()])
      .describe(
        "User-drawn polygon coordinates as [[lat, lng], [lat, lng], ...], minimum 3 points",
      ),
  ),
});
