/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { billComparisonResponseSchema } from "./billComparisonResponseSchema.ts";
import { bodyBillComparisonApiV1BillComparisonPostSchema } from "./bodyBillComparisonApiV1BillComparisonPostSchema.ts";

/**
 * @description Successful Response
 */
export const billComparisonApiV1BillComparisonPost200Schema = z
  .lazy(() => billComparisonResponseSchema)
  .describe("Bill comparison before/after solar installation.");

/**
 * @description Validation Error
 */
export const billComparisonApiV1BillComparisonPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
);

export const billComparisonApiV1BillComparisonPostMutationRequestSchema =
  z.lazy(() => bodyBillComparisonApiV1BillComparisonPostSchema);

export const billComparisonApiV1BillComparisonPostMutationResponseSchema =
  z.lazy(() => billComparisonApiV1BillComparisonPost200Schema);
