/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Bill comparison before/after solar installation.
 */
export const billComparisonResponseSchema = z
  .object({
    current_monthly_bill: z.number(),
    new_monthly_bill: z.number(),
  })
  .describe("Bill comparison before/after solar installation.");
