/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Equity data for a single Census block group.
 */
export const blockGroupEquityDataSchema = z
  .object({
    block_group_id: z.string(),
    lat: z.number().min(-90).max(90),
    lng: z.number().min(-180).max(180),
    equity_score: z.number().min(0).max(100),
    median_income: z.number(),
    renter_percentage: z.number(),
    energy_burden: z.number(),
    solar_installations: z.number().int(),
    total_households: z.number().int(),
    barriers: z.array(z.string()),
  })
  .describe("Equity data for a single Census block group.");
