/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const bodyBillComparisonApiV1BillComparisonPostSchema = z.object({
  file: z.instanceof(File).describe("Electricity bill PDF file"),
  first_year_savings_net: z.number().gt(0),
  payback_period_years: z.number().gt(0),
  monthly_savings: z.number().gt(0),
});
