/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Detailed breakdown of equity score components.
 */
export const equityScoreBreakdownSchema = z
  .object({
    total_score: z.number().min(0).max(100),
    income_component: z.number().min(0).max(40),
    ownership_component: z.number().min(0).max(30),
    burden_component: z.number().min(0).max(20),
    adoption_component: z.number().min(0).max(10),
    barriers: z.optional(z.array(z.string())),
  })
  .describe("Detailed breakdown of equity score components.");
