/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { blockGroupEquityDataSchema } from "./blockGroupEquityDataSchema.ts";
import { equityScoreBreakdownSchema } from "./equityScoreBreakdownSchema.ts";

/**
 * @description Response model for equity analysis API.
 */
export const equityAnalysisResponseSchema = z
  .object({
    user_address_score: z
      .lazy(() => equityScoreBreakdownSchema)
      .describe("Detailed breakdown of equity score components."),
    neighborhood_data: z.array(
      z
        .lazy(() => blockGroupEquityDataSchema)
        .describe("Equity data for a single Census block group."),
    ),
    solar_deserts_count: z
      .number()
      .int()
      .describe("Count of block groups with score < 35"),
    area_description: z.string().describe("e.g., 'Princeton, NJ area'"),
  })
  .describe("Response model for equity analysis API.");
