/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Key financial metrics derived from the financial analysis module.
 */
export const financialOutlookSchema = z
  .object({
    system_cost_net: z.number(),
    total_net_savings_25_years: z.number(),
    net_profit_25_years: z.number(),
    payback_period_years: z.number(),
    roi_25_years: z.number(),
    first_year_savings_gross: z.number(),
    first_year_savings_net: z.number(),
  })
  .describe(
    "Key financial metrics derived from the financial analysis module.",
  );
