/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Successful Response
 */
export const healthCheckHealthGet200Schema = z.any();

export const healthCheckHealthGetQueryResponseSchema = z.lazy(
  () => healthCheckHealthGet200Schema,
);
