/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { validationErrorSchema } from "./validationErrorSchema.ts";

export const HTTPValidationErrorSchema = z.object({
  detail: z.optional(z.array(z.lazy(() => validationErrorSchema))),
});
