/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Solar incentives and rebates search results.
 */
export const incentivesResponseSchema = z
  .object({
    analysis_id: z.string(),
    generated_at: z.string().datetime(),
    incentives_markdown: z.string(),
    model_name: z.string(),
  })
  .describe("Solar incentives and rebates search results.");
