/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Solar installers search results.
 */
export const installersResponseSchema = z
  .object({
    analysis_id: z.string(),
    generated_at: z.string().datetime(),
    installers_markdown: z.string(),
    model_name: z.string(),
  })
  .describe("Solar installers search results.");
