/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const locationSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  address: z.string(),
});
