/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const obstaclesSchema = z.object({
  chimneys: z.optional(z.number().int().default(0)),
  skylights: z.optional(z.number().int().default(0)),
  trees_nearby: z.optional(z.boolean().default(false)),
  hvac_units: z.optional(z.number().int().default(0)),
});
