/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Successful Response
 */
export const readRootGet200Schema = z.any();

export const readRootGetQueryResponseSchema = z.lazy(
  () => readRootGet200Schema,
);
