/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { roofPolygonSchema } from "./roofPolygonSchema.ts";

export const roofSegmentSchema = z.object({
  segment_id: z.number().int(),
  area_sqft: z.number(),
  orientation_degrees: z.number().int(),
  orientation_cardinal: z.string(),
  tilt_degrees: z.number(),
  panel_capacity: z.number().int(),
  polygon: z.optional(z.union([z.lazy(() => roofPolygonSchema), z.null()])),
});
