/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { obstaclesSchema } from "./obstaclesSchema.ts";
import { roofSegmentSchema } from "./roofSegmentSchema.ts";

export const roofAnalysisSchema = z.object({
  total_area_sqft: z.number(),
  usable_area_sqft: z.number(),
  roof_segments: z.array(z.lazy(() => roofSegmentSchema)),
  obstacles: z.lazy(() => obstaclesSchema),
  confidence_score: z.number(),
});
