/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Roof polygon coordinates for frontend Google Maps overlay
 */
export const roofPolygonSchema = z
  .object({
    coordinates: z.array(z.array(z.number())),
    area_sqft: z.number(),
    confidence: z.number(),
  })
  .describe("Roof polygon coordinates for frontend Google Maps overlay");
