/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const seasonalVariationSchema = z.object({
  summer_sun_hours: z.number(),
  winter_sun_hours: z.number(),
});
