/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Detailed breakdown of how solar score was calculated
 */
export const solarScoreBreakdownSchema = z
  .object({
    components: z.object({}).catchall(z.any()),
    formula: z.string(),
  })
  .describe("Detailed breakdown of how solar score was calculated");
