/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { seasonalVariationSchema } from "./seasonalVariationSchema.ts";

export const solarDataSchema = z.object({
  peak_sun_hours_daily: z.number(),
  annual_irradiance_kwh_m2: z.number(),
  seasonal_variation: z.lazy(() => seasonalVariationSchema),
});
