/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const solarPotentialSchema = z.object({
  system_size_kw: z.number(),
  annual_generation_kwh: z.number().int(),
  daily_generation_kwh: z.number(),
  capacity_factor: z.number(),
  energy_offset_percent: z.number().int(),
  co2_offset_tons_yearly: z.number(),
  co2_offset_tons_25year: z.number().int(),
  equivalent_trees_planted: z.number().int(),
});
