/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { financialOutlookSchema } from "./financialOutlookSchema.ts";
import { locationSchema } from "./locationSchema.ts";
import { solarPotentialSchema } from "./solarPotentialSchema.ts";

/**
 * @description Payload for requesting a Gemini-generated narrative summary.
 */
export const summaryRequestSchema = z
  .object({
    analysis_id: z.string(),
    location: z.lazy(() => locationSchema),
    solar_potential: z.lazy(() => solarPotentialSchema),
    financial_outlook: z
      .lazy(() => financialOutlookSchema)
      .describe(
        "Key financial metrics derived from the financial analysis module.",
      ),
    additional_context: z.optional(
      z
        .union([z.string(), z.null()])
        .describe("Optional free-form notes to steer the narrative tone."),
    ),
  })
  .describe("Payload for requesting a Gemini-generated narrative summary.");
