/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { HTTPValidationErrorSchema } from "./HTTPValidationErrorSchema.ts";
import { summaryRequestSchema } from "./summaryRequestSchema.ts";
import { summaryResponseSchema } from "./summaryResponseSchema.ts";

/**
 * @description Successful Response
 */
export const summarizeMetricsApiV1SummaryPost200Schema = z
  .lazy(() => summaryResponseSchema)
  .describe("Narrative summary generated by Gemini for the analysis metrics.");

/**
 * @description Validation Error
 */
export const summarizeMetricsApiV1SummaryPost422Schema = z.lazy(
  () => HTTPValidationErrorSchema,
);

export const summarizeMetricsApiV1SummaryPostMutationRequestSchema = z
  .lazy(() => summaryRequestSchema)
  .describe("Payload for requesting a Gemini-generated narrative summary.");

export const summarizeMetricsApiV1SummaryPostMutationResponseSchema = z.lazy(
  () => summarizeMetricsApiV1SummaryPost200Schema,
);
