/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Narrative summary generated by Gemini for the analysis metrics.
 */
export const summaryResponseSchema = z
  .object({
    analysis_id: z.string(),
    generated_at: z.string().datetime(),
    summary_markdown: z.string(),
    model_name: z.string(),
  })
  .describe("Narrative summary generated by Gemini for the analysis metrics.");
