from pydantic import BaseModel
from typing import List, Optional
from datetime import datetime
from models.equity_models import EquityAnalysisResponse

from models.financial import FinancialOutlook


class RoofPolygon(BaseModel):
    """Roof polygon coordinates for frontend Google Maps overlay"""
    coordinates: List[List[float]]  # [[lat, lng], [lat, lng], ...] in lat/lng format
    area_sqft: float
    confidence: float


class RoofSegment(BaseModel):
    segment_id: int
    area_sqft: float
    orientation_degrees: int
    orientation_cardinal: str
    tilt_degrees: float
    panel_capacity: int
    polygon: Optional[RoofPolygon] = None  # Polygon coordinates for frontend display


class Obstacles(BaseModel):
    chimneys: int = 0
    skylights: int = 0
    trees_nearby: bool = False
    hvac_units: int = 0


class RoofAnalysis(BaseModel):
    total_area_sqft: float
    usable_area_sqft: float
    roof_segments: List[RoofSegment]
    obstacles: Obstacles
    confidence_score: float


class SeasonalVariation(BaseModel):
    summer_sun_hours: float
    winter_sun_hours: float


class SolarData(BaseModel):
    peak_sun_hours_daily: float
    annual_irradiance_kwh_m2: float
    seasonal_variation: SeasonalVariation


class SolarPotential(BaseModel):
    system_size_kw: float
    annual_generation_kwh: int
    daily_generation_kwh: float
    capacity_factor: float
    energy_offset_percent: int
    co2_offset_tons_yearly: float
    co2_offset_tons_25year: int
    equivalent_trees_planted: int


class Location(BaseModel):
    latitude: float
    longitude: float
    address: str


class ScoreComponent(BaseModel):
    """Individual component of solar score calculation"""
    score: float
    weight: float
    weighted_score: float
    details: str


class SolarScoreBreakdown(BaseModel):
    """Detailed breakdown of how solar score was calculated"""
    components: dict  # Dict of component name -> ScoreComponent
    formula: str


class AnalysisResponse(BaseModel):
    analysis_id: str
    timestamp: datetime
    location: Location
    roof_analysis: RoofAnalysis
    solar_data: SolarData
    solar_potential: SolarPotential
    solar_score: int
    solar_score_breakdown: Optional[SolarScoreBreakdown] = None
    financial_outlook: FinancialOutlook
    equity_analysis: Optional[EquityAnalysisResponse] = None


class AgentsResponse(BaseModel):
    """Combined response from all agents"""
    agents_id: str
    timestamp: datetime
    analysis_id: str
    installer_results: str  # Raw agent output
    incentive_results: str  # Raw agent output
    status: str  # success, partial, failed
    errors: Optional[List[str]] = None


class SummaryResponse(BaseModel):
    """Narrative summary generated by Gemini for the analysis metrics."""
    analysis_id: str
    generated_at: datetime
    summary_markdown: str
    model_name: str


class InstallersResponse(BaseModel):
    """Solar installers search results."""
    analysis_id: str
    generated_at: datetime
    installers_markdown: str
    model_name: str


class IncentivesResponse(BaseModel):
    """Solar incentives and rebates search results."""
    analysis_id: str
    generated_at: datetime
    incentives_markdown: str
    model_name: str


class BillComparisonResponse(BaseModel):
    """Bill comparison before/after solar installation."""
    current_monthly_bill: float
    new_monthly_bill: float
